name: Update Commit Info

on:
  push:
    branches:
      - main
      - prod

env:
  GIT_USERNAME: reanbrenda
  GIT_EMAIL: mukindiabrenda67@gmail.com

jobs:
  update-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "${{ env.GIT_USERNAME }}"
          git config --global user.email "${{ env.GIT_EMAIL }}"

      - name: Create an empty commit
        run: |
          git commit --allow-empty -m "Update commit info"
          git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
